#!/usr/bin/env bash
# ── Generate version.ts from git tags ──
# Outputs:
#   "1.0.0"          — on an exact v1.0.0 tag
#   "1.0.0+3"        — 3 commits after v1.0.0
#   "0.0.0"          — no tags at all (clean fallback)
set -euo pipefail

OUTPUT="src/app/shared/lib/version.ts"

# Try to get the nearest v* tag, with distance if not exact
if VERSION=$(git describe --tags --match 'v*' --dirty 2>/dev/null); then
  # Strip leading 'v' — e.g., v1.0.0 → 1.0.0, v1.0.0-3-gabc → 1.0.0+3
  VERSION="${VERSION#v}"
  # Convert git describe format: 1.0.0-3-gabc1234 → 1.0.0+3
  VERSION="$(printf '%s' "$VERSION" | sed 's/-g[0-9a-f]\{7,\}$//; s/-/+/')"
else
  VERSION="0.0.0"
fi

cat > "$OUTPUT" <<EOF
/**
 * Auto-generated by scripts/gen-version.sh — do not edit manually.
 * Run \`pnpm build\` or \`pnpm start\` to regenerate.
 */
export const APP_VERSION = '${VERSION}';
EOF

echo "gen-version: generated $OUTPUT (v${VERSION})"
