#!/usr/bin/env bash
# ── Generate version.ts from git tags ──
# Outputs something like:
#   "1.0.0"          — on an exact tag
#   "1.0.0+3"        — 3 commits after v1.0.0
#   "gabc1234"       — no tags at all (fallback to commit hash)
set -euo pipefail

OUTPUT="src/app/shared/lib/version.ts"

# Try git describe: prefers annotated tags, falls back to short hash
if VERSION=$(git describe --tags --match 'v*' --always --dirty 2>/dev/null); then
  # Strip leading 'v' if present
  VERSION="${VERSION#v}"
else
  # Ultimate fallback
  VERSION="0.0.0"
fi

cat > "$OUTPUT" <<EOF
/**
 * Auto-generated by scripts/gen-version.sh — do not edit manually.
 * Run \`pnpm build\` or \`pnpm start\` to regenerate.
 */
export const APP_VERSION = '${VERSION}';
EOF

echo "gen-version: generated $OUTPUT (v${VERSION})"
